# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180117_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='\u5546\u54c1id', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='\u5546\u54c1'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(help_text='\u4e0a\u4f20\u7684\u6587\u4ef6', upload_to='message/images/', verbose_name='\u4e0a\u4f20\u7684\u6587\u4ef6'),
        ),
    ]
