# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180201_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='\u624b\u673a\u53f7\u7801', max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
