# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180119_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '\u9996\u9875\u5546\u54c1\u8f6e\u64ad\u56fe', 'verbose_name_plural': '\u9996\u9875\u5546\u54c1\u8f6e\u64ad\u56fe'},
        ),
    ]
